from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


def generate_report(
    filename,
    name,
    email,
    phone,
    linkedin,
    github,
    skills,
    education,
    certifications,
    score,
    suggestions,
    job_analysis=""
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    story = []

    # ------------------------
    # Title
    # ------------------------

    story.append(
        Paragraph("<b><font size=18>AI Resume Analyzer Report</font></b>", styles["Title"])
    )

    story.append(Spacer(1, 20))

    # ------------------------
    # Candidate Details
    # ------------------------

    story.append(Paragraph(f"<b>Name:</b> {name}", styles["Normal"]))
    story.append(Paragraph(f"<b>Email:</b> {email}", styles["Normal"]))
    story.append(Paragraph(f"<b>Phone:</b> {phone}", styles["Normal"]))
    story.append(Paragraph(f"<b>LinkedIn:</b> {linkedin}", styles["Normal"]))
    story.append(Paragraph(f"<b>GitHub:</b> {github}", styles["Normal"]))

    story.append(Spacer(1, 15))

    # ------------------------
    # ATS Score
    # ------------------------

    story.append(
        Paragraph(f"<b>ATS Score:</b> {score}/100", styles["Heading2"])
    )

    story.append(Spacer(1, 15))

    # ------------------------
    # Skills
    # ------------------------

    story.append(Paragraph("<b>Skills</b>", styles["Heading2"]))

    for skill in skills:
        story.append(
            Paragraph(f"• {skill}", styles["Normal"])
        )

    story.append(Spacer(1, 10))

    # ------------------------
    # Education
    # ------------------------

    story.append(Paragraph("<b>Education</b>", styles["Heading2"]))

    for edu in education:
        story.append(
            Paragraph(f"• {edu}", styles["Normal"])
        )

    story.append(Spacer(1, 10))

    # ------------------------
    # Certifications
    # ------------------------

    story.append(Paragraph("<b>Certifications</b>", styles["Heading2"]))

    for cert in certifications:
        story.append(
            Paragraph(f"• {cert}", styles["Normal"])
        )

    story.append(Spacer(1, 10))

    # ------------------------
    # Suggestions
    # ------------------------

    story.append(Paragraph("<b>Resume Suggestions</b>", styles["Heading2"]))

    for suggestion in suggestions:
        story.append(
            Paragraph(f"• {suggestion}", styles["Normal"])
        )

    story.append(Spacer(1, 15))

# ------------------------
# AI Job Analysis
# ------------------------



    story.append(
        Paragraph(
            "<b>AI Resume vs Job Analysis</b>",
            styles["Heading2"]
        )
    )

    for suggestion in suggestions:
        story.append(
            Paragraph(
                f"• {suggestion}",
                styles["Normal"]
            )
        )

    # AI Job Analysis
    if job_analysis:

        story.append(
            Paragraph(
                "<b>AI Resume vs Job Analysis</b>",
                styles["Heading2"]
            )
        )

        story.append(Spacer(1, 10))

        for line in job_analysis.split("\n"):

            line = line.strip()

            if line:

                story.append(
                    Paragraph(
                        line,
                        styles["Normal"]
                    )
                )

                story.append(Spacer(1, 5))

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<b>Generated by AI Resume Analyzer</b>",
            styles["Title"]
        )
    )

    doc.build(story)  